name: 🚀 Automatic STUGETHER Deploy on pull_request

on:
  pull_request:
    branches: 
      - master
      - main
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Deploy with Exclude Patterns
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:
        username: 'genius7'
        server: 'lupus.uberspace.de'
        ssh_private_key: ${{ secrets.DEPLOY_TO_UBERSPACE_SSH_KEY }}
        local_path: './*'
        remote_path: '/home/genius7/Applications/stugether.online/'
        rsyncArgs: '--exclude=node_modules --exclude=.git --exclude=*.log'
        sftpArgs: '-o ConnectTimeout=5'
        
